### ISSUE TITLE
PSNR and SSIM

### ISSUE THREAD

**Issue by ronjonxu** [NeonLeexiang/DLGSANet#1]
Dear author,
I have a question about the the PSNR and SSIM values of SWINIR.  In your paper,  the PSNR values of SWINIR in all datesets(like Set5, Set14...) are different from the original paper of SWINIR, but the PSNR values of the common models(like RCAN, SAN, HAN) of your paper and the paper of SWINIR remain same for all datasets.

**Comment by NeonLeexiang** [comment]
the PSNR and SSIM values of models in the table are trained with DIV2K not DF2K

**Comment by ronjonxu** [comment]
Thank you for your quick reply, it's my negligence.
