### ISSUE TITLE
About model code

### ISSUE THREAD

**Issue by Thothene** [NeonLeexiang/DLGSANet#11]
Thank you for nice work. I can't find the code for DLGSANet. Can you tell me which file it is in？

**Comment by NeonLeexiang** [comment]
We appreciated your comments. 

The DLGSANet's network architecture can be found in basicsr/archs/dlgsanet_arch.py, while the MHDLSA's utils file can be found in basicsr/archs/dlgsanet_idynamicdwconv_util.py.

**Comment by Thothene** [comment]
Thank you very much. Wishing you all the best Achievements.
