### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by cenchaojun** [NeonLeexiang/DLGSANet#2]
thank you for nice work. when would you release the codes?

**Comment by NeonLeexiang** [comment]
非常感谢你关注这项工作

目前代码还没来得及整理，如果需要的话，以下是代码实现的一些基本信息：

这项工作的模型训练是基于 BasicSR框架：
[[BasicSR](https://github.com/XPixelGroup/BasicSR)](https://github.com/XPixelGroup/BasicSR) 得益于[[XPixelGroup](https://github.com/XPixelGroup)](https://github.com/XPixelGroup) 的杰出贡献。

关于MHDLSA的实现是基于以下工作:

_On the Connection between Local Attention and Dynamic Depth-wise Convolution_ [[paper](https://arxiv.org/abs/2106.04263)](https://arxiv.org/abs/2106.04263) [[github](https://github.com/Atten4Vis/DemystifyLocalViT)](https://github.com/Atten4Vis/DemystifyLocalViT)

SparseGSA的实现是基于以下工作:

_Restormer: Efficient Transformer for High-Resolution Image Restoration_ [[paper](https://arxiv.org/abs/2111.09881)](https://arxiv.org/abs/2111.09881) [[github](https://github.com/swz30/Restormer)](https://github.com/swz30/Restormer)

_Improving Image Restoration by Revisiting Global Information Aggregation_ [[paper](https://arxiv.org/abs/2112.04491)](https://arxiv.org/abs/2112.04491) [[github](https://github.com/megvii-research/TLC)](https://github.com/megvii-research/TLC)



We sincerely appreciate your interest in our efforts.

We haven't had chance to organize the code as of yet. The following is some fundamental knowledge about how the code is implemented, should it be needed:

The foundation for the training process is [[BasicSR](https://github.com/XPixelGroup/BasicSR)](https://github.com/XPixelGroup/BasicSR) , which profited from the outstanding contribution of [[XPixelGroup](https://github.com/XPixelGroup)](https://github.com/XPixelGroup) .

The following research forms the foundation for the MHDLSA implementation:

_On the Connection between Local Attention and Dynamic Depth-wise Convolution_ [[paper](https://arxiv.org/abs/2106.04263)](https://arxiv.org/abs/2106.04263) [[github](https://github.com/Atten4Vis/DemystifyLocalViT)](https://github.com/Atten4Vis/DemystifyLocalViT)

And the following research forms the foundation for the Sparse implementation:

_Restormer: Efficient Transformer for High-Resolution Image Restoration_ [[paper](https://arxiv.org/abs/2111.09881)](https://arxiv.org/abs/2111.09881) [[github](https://github.com/swz30/Restormer)](https://github.com/swz30/Restormer)

_Improving Image Restoration by Revisiting Global Information Aggregation_ [[paper](https://arxiv.org/abs/2112.04491)](https://arxiv.org/abs/2112.04491) [[github](https://github.com/megvii-research/TLC)](https://github.com/megvii-research/TLC)

**Comment by cenchaojun** [comment]
> 非常感谢你关注这项工作
> 
> 目前代码还没来得及整理，如果需要的话，以下是代码实现的一些基本信息：
> 
> 这项工作的模型训练是基于 BasicSR框架： [[BasicSR](https://github.com/XPixelGroup/BasicSR)](https://github.com/XPixelGroup/BasicSR) 得益于[[XPixelGroup](https://github.com/XPixelGroup)](https://github.com/XPixelGroup) 的杰出贡献。
> 
> 关于MHDLSA的实现是基于以下工作:
> 
> _On the Connection between Local Attention and Dynamic Depth-wise Convolution_ [[paper](https://arxiv.org/abs/2106.04263)](https://arxiv.org/abs/2106.04263) [[github](https://github.com/Atten4Vis/DemystifyLocalViT)](https://github.com/Atten4Vis/DemystifyLocalViT)
> 
> SparseGSA的实现是基于以下工作:
> 
> _Restormer: Efficient Transformer for High-Resolution Image Restoration_ [[paper](https://arxiv.org/abs/2111.09881)](https://arxiv.org/abs/2111.09881) [[github](https://github.com/swz30/Restormer)](https://github.com/swz30/Restormer)
> 
> _Improving Image Restoration by Revisiting Global Information Aggregation_ [[paper](https://arxiv.org/abs/2112.04491)](https://arxiv.org/abs/2112.04491) [[github](https://github.com/megvii-research/TLC)](https://github.com/megvii-research/TLC)
> 
> We sincerely appreciate your interest in our efforts.
> 
> We haven't had chance to organize the code as of yet. The following is some fundamental knowledge about how the code is implemented, should it be needed:
> 
> The foundation for the training process is [[BasicSR](https://github.com/XPixelGroup/BasicSR)](https://github.com/XPixelGroup/BasicSR) , which profited from the outstanding contribution of [[XPixelGroup](https://github.com/XPixelGroup)](https://github.com/XPixelGroup) .
> 
> The following research forms the foundation for the MHDLSA implementation:
> 
> _On the Connection between Local Attention and Dynamic Depth-wise Convolution_ [[paper](https://arxiv.org/abs/2106.04263)](https://arxiv.org/abs/2106.04263) [[github](https://github.com/Atten4Vis/DemystifyLocalViT)](https://github.com/Atten4Vis/DemystifyLocalViT)
> 
> And the following research forms the foundation for the SparseGSA implementation:
> 
> _Restormer: Efficient Transformer for High-Resolution Image Restoration_ [[paper](https://arxiv.org/abs/2111.09881)](https://arxiv.org/abs/2111.09881) [[github](https://github.com/swz30/Restormer)](https://github.com/swz30/Restormer)
> 
> _Improving Image Restoration by Revisiting Global Information Aggregation_ [[paper](https://arxiv.org/abs/2112.04491)](https://arxiv.org/abs/2112.04491) [[github](https://github.com/megvii-research/TLC)](https://github.com/megvii-research/TLC)

谢谢您分享的教程。❤️
