### ISSUE TITLE
light-version options

### ISSUE THREAD

**Issue by Lucien66** [NeonLeexiang/DLGSANet#7]
HI! thanks for your work!
I am trying to test the inference time and max memory of light-dlgsanet on my device. could you please release the options of light version.

**Comment by NeonLeexiang** [comment]
Details on the light-version implement are in the paper. 

> When the numbers of the RHDTG, the HDTB, and the feature channel are set to be 3, 3, and 48, respectively, we refer to the DLGSANet as DLGSANet-tiny. When the numbers of the RHDTG, the HDTB, and the feature channel are set to be 4, 3, and 48, respectively, we refer to the DLGSANet as DLGSANet-light.

In our experiments, we discovered that our DLGSANet performs better than RCAN, EDSR, etc. when [channels, groups, blocks] are set to [60, 4, 3].

We're nearly finished with the last of our work's code.
